version: '3.5'
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-windscribe1
    restart: unless-stopped
    previleged: true
    ports:
      - 9091:9091
    volumes:
      - /media/torr:/data
      - /docker/transmission-openvpn:/etc/openvpn/custom:ro
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - OPENVPN_USERNAME=windscribe1
      - OPENVPN_PASSWORD=windscribe1
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_CONFIG=config
      - GLOBAL_APPLY_PERMISSIONS=true
      - TRANSMISSION_HOME=/data/transmission-home
      - TRANSMISSION_RPC_PORT=9091
      - TRANSMISSION_DOWNLOAD_DIR=/data/completed
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_WATCH_DIR=/data/watch
      - WEBPROXY_ENABLED=false
      - WEBPROXY_PORT=8888
      - WEBPROXY_USERNAME=transmission
      - WEBPROXY_PASSWORD=transmission
      - LOG_TO_STDOUT=false
      - HEALTH_CHECK_HOST=google.com
      - CREATE_TUN_DEVICE=true
      - ENABLE_UFW=false
      - UFW_ALLOW_GW_NET=false
      - UFW_EXTRA_PORTS=3306
      - UFW_DISABLE_IPTABLES_REJECT=false
      - DROP_DEFAULT_ROUTE=true
      - PUID=1032
      - PGID=100
      - LOCAL_NETWORK=192.168.0.0/24
    network_mode: bridge
